### ISSUE TITLE
compatibility for paper, bukki, spigot.

### ISSUE THREAD

**Issue by Aicrag24** [maxvar/mfc-easyfeed#10]
Hi, I'm aicrag.

I really liked the mod you made so that animals can eat by throwing food on the floor.

I would like to know if it will be possible for it to be compatible with the other versions of minecraft, spigot, bukki or paper, since the server that I need to use with another mod only works with those mentioned u.u.

I will wait for your answer :)

**Comment by maxvar** [comment]
I have no intent to extend the compatibility of this mod beyond fabric loader for vanilla.
If you desperately want to use it on an papermc server with a plugin you like so much, you can try Velocity  https://docs.papermc.io/velocity/server-compatibility
