### ISSUE TITLE
Wont Work?

### ISSUE THREAD

**Issue by firestorm2039** [maxvar/mfc-easyfeed#7]
i have latest 1.18.1 mod of this and latest 1.18.1 of forge.

i place wheat down for cows, seeds for chickens, carrots for pigs etc, but they just walk over it?? any ideas??

**Comment by maxvar** [comment]
this is a fabric, not forge mod

**Comment by firestorm2039** [comment]
oh ok, sorry i didnt realise, usually minecraft informs me if i have a fabric mod in the folder?, how do i check if its a fabric mod before downloading? do you know of any forge 1s for 1.18.1?

**Comment by maxvar** [comment]
If you dl from curseforge it clearly shows fabric or forge in 'versions'.
I don't know a current forge mod which is exactly like mine, but you can try https://www.curseforge.com/minecraft/mc-mods/animal-feeding-trough.
Once there was https://www.curseforge.com/minecraft/mc-mods/easy-breeding but it stopped updating after mc1.17 (which originally prompted me to create my mod).
